name: Build

on:
  pull_request: {}
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          repository: "p6m7g8-dotfiles/p6common"
          path: ".deps/p6common"
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          repository: "p6m7g8-dotfiles/p6aws"
          path: ".deps/paws"
      - name: CDK Build
        uses: p6m7g8-actions/cdk-build@main
        with:
          aws_region: ${{ secrets.CDK_DEPLOY_REGION }}
          aws_role: ${{ secrets.AWS_ROLE }}
          aws_session_name: ${{ secrets.AWS_SESSION_NAME }}
          cdk_deploy_account: ${{ secrets.CDK_DEPLOY_ACCOUNT }}
          cdk_deploy_region: ${{ secrets.CDK_DEPLOY_REGION }}
          p6_custom_build_cmd: "bin/p6lzctl build"
